# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_ta_ilosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='stolarnia_modelarnia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='szwalnia_modelarnia',
            field=models.BooleanField(default=False),
        ),
    ]
