# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spotkania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.TextField(default=None)),
                ('nazwisko', models.TextField(default=None)),
                ('data_rozmowy', models.DateField(default=None)),
                ('godzina_rozmowy', models.TimeField(default=None)),
            ],
        ),
    ]
