# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_rekrutacyjna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotkania',
            name='data_rozmowy',
            field=models.DateTimeField(),
        ),
    ]
