# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_rekrutacyjna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotkania',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
