# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_rekrutacyjna', '0002_auto_20170116_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotkania',
            name='osoba',
        ),
        migrations.AddField(
            model_name='spotkania',
            name='godzina_rozmowy',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='spotkania',
            name='imie',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='spotkania',
            name='nazwisko',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='spotkania',
            name='data_rozmowy',
            field=models.DateField(default=None),
        ),
    ]
